Repository GrebbMe/grabbme-be, pull requests merged in 2024-10, with the labels that each got.

#39 [REFACTOR] board 서비스 posts Transactional Decorator 적용
  apps/api-gateway/src/board/board.controller.ts
  apps/api-gateway/src/board/board.service.ts
  apps/board/src/app.module.ts
  apps/board/src/board/board.service.ts
  apps/board/src/main.ts
Labels: 🔨 refactor

#35 [FEAT] 채팅방 생성 기능 구현
  apps/api-gateway/src/chat/chat.controller.ts
  apps/api-gateway/src/chat/chat.service.ts
  apps/api-gateway/src/chat/dto/req.dto.ts
  apps/api-gateway/src/main.ts
  apps/chat/src/app.module.ts
  apps/chat/src/chat/chat.controller.ts
  apps/chat/src/chat/chat.module.ts
  apps/chat/src/chat/chat.service.ts
  apps/chat/src/chat/entity/chat-room.entity.ts
  apps/chat/src/config/mongo.config.ts
  shared/constants/chat-constants.ts
  shared/constants/message-pattern.ts
Labels: ✨ feat

#32 [FEAT] user 테이블 생성 & user entity 정의
  apps/user/src/user/entities/user.entity.ts
Labels: ✨ feat

#42 [FEAT] user 생성 API 구현
  apps/api-gateway/src/user/dto/create-user.dto.ts
  apps/api-gateway/src/user/dto/req.dto.ts
  apps/api-gateway/src/user/dto/update-user.dto.ts
  apps/api-gateway/src/user/entities/user.entity.ts
  apps/api-gateway/src/user/user.controller.ts
  apps/api-gateway/src/user/user.service.ts
  apps/user/src/app.module.ts
  apps/user/src/main.ts
  apps/user/src/user/dto/create-user.dto.ts
  apps/user/src/user/dto/req.dto.ts
  apps/user/src/user/entities/user.entity.ts
  apps/user/src/user/user.controller.ts
  apps/user/src/user/user.module.ts
  apps/user/src/user/user.service.ts
  apps/user/tsconfig.app.json
  nest-cli.json
  shared/constants/message-pattern.ts
Labels: ✨ feat

#47 [TEST] 채팅방 생성 기능 테스트 작성
  apps/api-gateway/src/chat/chat.controller.spec.ts
  apps/api-gateway/src/chat/chat.service.spec.ts
  apps/chat/src/chat/chat.controller.spec.ts
  apps/chat/src/chat/chat.controller.ts
  apps/chat/src/chat/chat.service.spec.ts
  apps/chat/src/chat/chat.service.ts
  apps/chat/src/chat/dto/req.dto.ts
Labels: ✅ test, ✨ feat, 🔄move

#46 [FEAT] chat 서비스 채팅방/채팅리스트 조회 구현
  apps/api-gateway/src/chat/chat.controller.ts
  apps/api-gateway/src/chat/chat.service.ts
  apps/api-gateway/src/chat/dto/req.dto.ts
  apps/chat/src/chat/chat.controller.ts
  apps/chat/src/chat/chat.gateway.ts
  apps/chat/src/chat/chat.module.ts
  apps/chat/src/chat/chat.service.ts
  apps/chat/src/chat/entities/chat-list.entity.ts
  apps/chat/src/chat/entities/chat-room.entity.ts
  apps/chat/src/chat/entities/chat.entity.ts
  shared/constants/chat-constants.ts
  shared/constants/message-pattern.ts
Labels: ✨ feat, 🛠️ fix, 💬 comment

#49 [FEAT] user api 구현
  apps/api-gateway/src/user/dto/req.dto.ts
  apps/api-gateway/src/user/entities/user.entity.ts
  apps/api-gateway/src/user/user.controller.ts
  apps/api-gateway/src/user/user.service.ts
  apps/user/src/main.ts
  apps/user/src/user/dto/req.dto.ts
  apps/user/src/user/entities/user.entity.ts
  apps/user/src/user/user.controller.ts
  apps/user/src/user/user.module.ts
  apps/user/src/user/user.service.ts
  shared/constants/message-pattern.ts
Labels: ✨ feat

#51 [TEST] chat 서비스 채팅방/채팅리스트 조회 테스트코드 구현
  apps/chat/src/chat/chat.controller.spec.ts
  apps/chat/src/chat/chat.controller.ts
  apps/chat/src/chat/chat.service.spec.ts
  apps/chat/src/chat/dto/req.dto.ts
  shared/constants/mock-example.ts
Labels: ✅ test, 🛠️ fix

#54 [FEAT] board 서비스 post_category_id에 따른 분기 처리
  apps/api-gateway/src/board/board.controller.ts
  apps/api-gateway/src/board/board.service.ts
  apps/api-gateway/src/board/dto/create-board.dto.ts
  apps/api-gateway/src/board/dto/req.dto.ts
  apps/api-gateway/src/board/dto/update-board.dto.ts
  apps/board/src/board/board.controller.ts
  apps/board/src/board/board.module.ts
  apps/board/src/board/board.service.ts
  apps/board/src/board/dto/create-board.dto.ts
  apps/board/src/board/dto/req.dto.ts
  apps/board/src/board/dto/update-board.dto.ts
  apps/board/src/board/entities/board.entity.ts
  shared/constants/message-pattern.ts
Labels: ✨ feat

#58 [FEAT] 채팅 전송/수신 기능 구현
  apps/chat/src/chat/chat.gateway.ts
  apps/chat/src/chat/chat.module.ts
  apps/chat/src/chat/chat.service.ts
  apps/chat/src/chat/entities/chat-list.entity.ts
  apps/chat/src/main.ts
  shared/constants/chat-constants.ts
Labels: ✨ feat

#53 [FEAT] 인증/인가를 위한 Strategy, Guard 구현
  apps/api-gateway/src/app.module.ts
  apps/api-gateway/src/auth/auth.controller.ts
  apps/api-gateway/src/auth/auth.module.ts
  apps/api-gateway/src/auth/auth.service.ts
  apps/api-gateway/src/auth/guards/github.guard.ts
  apps/api-gateway/src/auth/guards/jwt-auth.guard.ts
  apps/api-gateway/src/auth/guards/jwt-refresh-auth.guard.ts
  apps/api-gateway/src/auth/strategies/github.strategy.ts
  apps/api-gateway/src/auth/strategies/jwt-refresh.strategy.ts
  apps/api-gateway/src/auth/strategies/jwt.strategy.ts
  apps/api-gateway/src/auth/types/jwt.type.ts
  apps/api-gateway/src/auth/types/user.type.ts
  apps/api-gateway/src/common/filter/gateway-rpc-exception.filter.ts
  apps/api-gateway/src/config/client.config.ts
  apps/api-gateway/src/config/github.config.ts
  apps/api-gateway/src/config/index.ts
  apps/api-gateway/src/config/jwt.config.ts
  apps/api-gateway/src/main.ts
  apps/api-gateway/src/user/dto/req.dto.ts
  apps/api-gateway/src/user/entities/user.entity.ts
  apps/api-gateway/src/user/user.controller.ts
  apps/api-gateway/src/user/user.module.ts
  apps/api-gateway/src/user/user.service.ts
  apps/user/src/user/dto/req.dto.ts
  apps/user/src/user/dto/update-user.dto.ts
  apps/user/src/user/entities/temp-user.entity.ts
  apps/user/src/user/entities/user.entity.ts
  apps/user/src/user/user.controller.ts
  apps/user/src/user/user.module.ts
  apps/user/src/user/user.service.ts
  package-lock.json
  package.json
  shared/constants/message-pattern.ts
Labels: ✨ feat

#62 [CONFIG] 배포를 위한 코드 설정
  .github/workflows/build-ec2.yml
  .gitignore
  apps/api-gateway/src/user/user.controller.ts
  apps/api-gateway/src/user/user.service.ts
  apps/user/src/user/dto/req.dto.ts
  apps/user/src/user/user.controller.ts
  apps/user/src/user/user.service.ts
  package-lock.json
  package.json
Labels: ⚙️ config

#61 [FEAT] board 서비스 Exception Filter 적용
  apps/api-gateway/src/board/board.service.ts
  apps/board/src/board/board.controller.ts
  apps/board/src/board/board.module.ts
  apps/board/src/board/board.service.ts
  apps/board/src/main.ts
  shared/constants/message-pattern.ts
Labels: ✨ feat

#65 [FEAT] 채팅방 삭제 기능 구현
  apps/api-gateway/src/chat/chat.controller.ts
  apps/api-gateway/src/chat/chat.service.ts
  apps/chat/src/chat/chat.controller.ts
  apps/chat/src/chat/chat.gateway.ts
  apps/chat/src/chat/chat.module.ts
  apps/chat/src/chat/chat.service.ts
  apps/chat/src/chat/dto/req.dto.ts
  apps/chat/src/main.ts
  shared/constants/message-pattern.ts
Labels: ✨ feat, 🛠️ fix

#67 [FEAT] 프로젝트 게시글 생성 시 팀 및 참가자 관리 기능 구현
  apps/api-gateway/src/board/board.controller.ts
  apps/api-gateway/src/board/board.service.ts
  apps/api-gateway/src/board/dto/req.dto.ts
  apps/board/src/board/board.controller.ts
  apps/board/src/board/board.module.ts
  apps/board/src/board/board.service.ts
  apps/board/src/board/dto/req.dto.ts
  apps/board/src/board/entities/board.entity.ts
  apps/board/src/board/entities/index.ts
  apps/board/src/board/entities/participant.entity.ts
  apps/board/src/board/entities/team.entity.ts
  shared/constants/message-pattern.ts
Labels: ✨ feat

#69 [refactor] 채팅 관련 유지보수
  apps/chat/src/chat/chat.gateway.ts
  apps/chat/src/chat/chat.service.spec.ts
  apps/chat/src/chat/chat.service.ts
  shared/constants/chat-constants.ts
Labels: 🔨 refactor, ✨ feat, 🛠️ fix

#70 [FEAT] Query로 게시글 리스트 조회
  apps/api-gateway/src/board/board.controller.ts
  apps/api-gateway/src/board/board.service.ts
  apps/board/src/board/board.controller.ts
  apps/board/src/board/board.service.ts
Labels: ✨ feat
